### ISSUE TITLE
Keyerror: "i'm" 

### ISSUE THREAD

**Issue by frankfufuu** [talk2car/Talk2Car#3] opened 2021-06-01 13:16 UTC
When I try to train c4av_model by command python train.py --root ./data --lr 0.01 --nesterov --evaluate, there is bug occur:
![eb1e357a8a8b003f808defe84bab20f](https://user-images.githubusercontent.com/51686116/120329848-d54d9a00-c31e-11eb-8c86-a52efa0431cb.png)

**Comment by ThierryDeruyttere** [comment] 2021-06-01 13:44
Hello,

Thanks for your interest in Talk2Car. 
To try to reproduce your error, I did a clean clone of the repository and installed the images as per the README and also the packages in requirements.txt.
I'm currently training the c4av_model.py with the same command as you are and I'm not having any issues. 
Could you please check if your packages are *at least* the same version as in our requirements.txt? If that didn't work, could you maybe try with a clean clone of the repository? 
Please let me know if this helped or not. 

Best,

Thierry

**Comment by frankfufuu** [comment] 2021-06-02 11:12
Hi
Thanks for replying.
I did a clean clone and change the vision of package according to requirement.txt except torch(1.8.1+cu111) and torchvision(0.9.1+cu111)
Here are some errors and i made some changes to the code for run successfully in my environment:

Firstly, 
![fd4152ea6e933a8ffeb76bd191609cc](https://user-images.githubusercontent.com/51686116/120466781-0cc94e80-c3d2-11eb-8448-f156b94d99a7.png)
so I write the main() into if __name__ == '__main__' and it works
![wechat_20210602184234](https://user-images.githubusercontent.com/51686116/120467046-587bf800-c3d2-11eb-8472-9aca2b2c2081.png)

Secondly,
There is error that CUDA is out of memory
![wechat_20210602184601](https://user-images.githubusercontent.com/51686116/120467620-f243a500-c3d2-11eb-9aeb-ca059a8dfde5.png)
So I change the batch_size from 18 to 6 and it works (Perhaps it is the problem from vision of torch and torch vision packages)
![wechat_20210602184950](https://user-images.githubusercontent.com/51686116/120468025-5bc3b380-c3d3-11eb-9444-45fe1a6ef720.png)

Thirdly,
There is error when input tensor:
![wechat_20210602185554](https://user-images.githubusercontent.com/51686116/120468795-2ff4fd80-c3d4-11eb-8320-4452bbeec997.png)
So I add .cpu() after input_lengths in nlp_models.py and it works
![image](https://user-images.githubusercontent.com/51686116/120469019-6e8ab800-c3d4-11eb-9efa-a66061e30219.png)

Finally, there is keyerror:'i‘m' occur while the model is training
i think it is encoding probem: "i‘m" is not equal to "i'm". So i add .replace("i‘m","i'm") in vocabulary.py:
new = [self.w2ix[x.text] for x in self.nlp(sentence.replace("i‘m","i'm"))] but the error still occur
Also, I try to add key "i'm" and "i’m" in the vocabulary.txt but it does not work

I am still confused on this KeyError bug

**Comment by ThierryDeruyttere** [comment] 2021-06-02 13:14
Hi,

Thanks for the images and the explanation! I have also updated to PyTorch 1.8.1 and this apparently lead to some issue with NumPy/spacy and also to the error in the code as you have posted about the lengths and the key error.
Apparently, something has changed in the newest spacy versions compared to the version that we are using.  
Downgrading to our spacy version resolved the key error.

I have updated the repo to work with pytorch 1.8.1 and I also updated the requirement.txt file. Please have a look at it. It is very important that you use the *same* spacy version as we are. Please let me know if this helped.

**Comment by ThierryDeruyttere** [comment] 2021-06-08 08:10
@frankfufuu is this issue solved?

**Comment by frankfufuu** [comment] 2021-06-14 09:52
hi,
I change all packages version matching with the requiremnt.txt ( pytorch=1.4.0 torchvision=0.5.0 spacy=2.2.4)
but the KeyError: 'i'm' still occur

**Comment by ThierryDeruyttere** [comment] 2021-06-14 14:59
Hi there,

The versions you are mentioning are not what is currently in the requirements.txt (https://github.com/talk2car/Talk2Car/blob/master/c4av_model/requirements.txt).
Did you start from a clean clone *after* my message 12 days ago?

To help you, I have also created a google collab (https://colab.research.google.com/drive/19wTtGskfdhZWvNIfIrUcpwe9IChRKBtQ?usp=sharing) where you can run our code without any issues.

**Comment by ThierryDeruyttere** [comment] 2021-08-03 06:52
Since there hasn't been a message for a while, I'll close this issue. If there is a problem, please reopen this issue.

**Closed by ThierryDeruyttere** 2021-08-03 06:52 UTC

**Comment by yuchen2199** [comment] 2021-09-25 10:26
I change all packages version matching with the requirement.txt(torch==1.8.1... )
but I also meet the same question.
